import { Bodoni_Moda } from "next/font/google";
import "./globals.css";

const bodoni_Moda = Bodoni_Moda({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "my-blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodoni_Moda.className}>{children}</body>
    </html>
  );
}
